# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
#org.gradle.parallel=true
org.gradle.caching=false
org.gradle.caching.debug=false
org.gradle.parallel=false
#org.gradle.configureondemand=true

#systemProp.socksProxyHost=127.0.0.1
#systemProp.socksProxyPort=9050

# Mod properties
mod.version=6.3.1
mod.group=eu.midnightdust
mod.id=blur
mod.name=Blur+

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title=[VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets=[VERSIONED]

# Mod setup
deps.fabric_loader=0.19.3
deps.fabric_version=[VERSIONED]

deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.midnightlib_version=1.9.3

# Publishing
publish.modrinth=NK39zBp2
publish.curseforge=393563