# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.11
supported_versions=1.21.11
yarn_mappings=1.21.11+build.3
enabled_platforms=fabric,neoforge

# Mod Properties
mod_version=1.0.0+1.21.11
maven_group=eu.midnightdust.blur
archives_base_name=blur-perfected
release_type=release
curseforge_id=393563
modrinth_id=NK39zBp2

# Modloaders
fabric_loader_version=0.17.3
fabric_api_version=0.139.4+1.21.11

neoforge_version=21.9.11-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Libraries
midnightlib_version = 1.9.2+1.21.11-fabric
modmenu_version = 17.0.0-alpha.1
