modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "blur"
version = "${version}"
displayName = "Blur Perfected"
logoFile = "blur.png"
authors = "Motschen, amiralimollaei, tterrag1098, Pyrofab, backryun, byquanton"
description = '''
Various enhancements for the blur effect behind Minecraft GUIs
'''

[[mixins]]
config = "blur.mixins.json"

[[dependencies.blurperfected]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blurperfected]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blurperfected]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.9.2,)"
ordering = "NONE"
side = "CLIENT"