modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "blur"
version = "${version}"
displayName = "Blur+"
logoFile = "blur.png" # legacy for older versions, use bannerFile for 26.3
iconFile = "assets/blur/icon.png"
bannerFile = "blur.png"
authors = "Motschen, amiralimollaei, tterrag1098, Pyrofab, backryun, byquanton"
description = '''
Various enhancements for the blur effect behind Minecraft GUIs
'''

[[mixins]]
config = "blur.mixins.json"

[[dependencies.blur]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blur]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blur]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.9.3,)"
ordering = "NONE"
side = "CLIENT"