modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "blurperfected"
version = "${version}"
displayName = "Blur Perfected"
logoFile = "blur-perfected.png"
authors = "Motschen, tterrag1098, Pyrofab, backryun, byquanton, amiralimollaei"
description = '''
Various enhancements for the blur effect behind Minecraft GUIs
'''

[[mixins]]
config = "blur.mixins.json"

[[dependencies.blurperfected]]
modId = "neoforge"
mandatory = true
versionRange = "[21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blurperfected]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blurperfected]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.9.2,)"
ordering = "NONE"
side = "CLIENT"